// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/background.js"
    | "/content-scripts/content.js"
    | "/google-logo.svg"
    | "/icon-16.png"
    | "/icon-32.png"
    | "/sidepanel.html"
    | "/youload-login.png"
    | "/youload-logo.svg"
    | "/youload-readme-short.png"
    | "/youload-readme-video.png"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
