/* tslint:disable */
/* eslint-disable */
/**
 * YT Download Service
 * Allows a google authenticated user to download videos from YouTube.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jijimotte@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Model for an audio format option.
 * @export
 * @interface AudioOption
 */
export interface AudioOption {
    /**
     * 
     * @type {string}
     * @memberof AudioOption
     */
    formatId: string;
    /**
     * 
     * @type {string}
     * @memberof AudioOption
     */
    note?: string | null;
}

/**
 * Check if a given object implements the AudioOption interface.
 */
export function instanceOfAudioOption(value: object): value is AudioOption {
    if (!('formatId' in value) || value['formatId'] === undefined) return false;
    return true;
}

export function AudioOptionFromJSON(json: any): AudioOption {
    return AudioOptionFromJSONTyped(json, false);
}

export function AudioOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AudioOption {
    if (json == null) {
        return json;
    }
    return {
        
        'formatId': json['format_id'],
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function AudioOptionToJSON(json: any): AudioOption {
    return AudioOptionToJSONTyped(json, false);
}

export function AudioOptionToJSONTyped(value?: AudioOption | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'format_id': value['formatId'],
        'note': value['note'],
    };
}

