/* tslint:disable */
/* eslint-disable */
/**
 * YT Download Service
 * Allows a google authenticated user to download videos from YouTube.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jijimotte@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Pydantic model for a download request.
 * @export
 * @interface DownloadRequest
 */
export interface DownloadRequest {
    /**
     * 
     * @type {string}
     * @memberof DownloadRequest
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof DownloadRequest
     */
    formatId?: string | null;
}

/**
 * Check if a given object implements the DownloadRequest interface.
 */
export function instanceOfDownloadRequest(value: object): value is DownloadRequest {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function DownloadRequestFromJSON(json: any): DownloadRequest {
    return DownloadRequestFromJSONTyped(json, false);
}

export function DownloadRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DownloadRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'formatId': json['format_id'] == null ? undefined : json['format_id'],
    };
}

export function DownloadRequestToJSON(json: any): DownloadRequest {
    return DownloadRequestToJSONTyped(json, false);
}

export function DownloadRequestToJSONTyped(value?: DownloadRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'format_id': value['formatId'],
    };
}

