/* tslint:disable */
/* eslint-disable */
/**
 * YT Download Service
 * Allows a google authenticated user to download videos from YouTube.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jijimotte@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Model for Google OAuth token.
 * @export
 * @interface GoogleToken
 */
export interface GoogleToken {
    /**
     * 
     * @type {string}
     * @memberof GoogleToken
     */
    token: string;
}

/**
 * Check if a given object implements the GoogleToken interface.
 */
export function instanceOfGoogleToken(value: object): value is GoogleToken {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function GoogleTokenFromJSON(json: any): GoogleToken {
    return GoogleTokenFromJSONTyped(json, false);
}

export function GoogleTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoogleToken {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function GoogleTokenToJSON(json: any): GoogleToken {
    return GoogleTokenToJSONTyped(json, false);
}

export function GoogleTokenToJSONTyped(value?: GoogleToken | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

