/* tslint:disable */
/* eslint-disable */
/**
 * YT Download Service
 * Allows a google authenticated user to download videos from YouTube.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jijimotte@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Pydantic model for validating a YouTube video URL.
 * @export
 * @interface VideoURL
 */
export interface VideoURL {
    /**
     * 
     * @type {string}
     * @memberof VideoURL
     */
    url: string;
}

/**
 * Check if a given object implements the VideoURL interface.
 */
export function instanceOfVideoURL(value: object): value is VideoURL {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function VideoURLFromJSON(json: any): VideoURL {
    return VideoURLFromJSONTyped(json, false);
}

export function VideoURLFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoURL {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
    };
}

export function VideoURLToJSON(json: any): VideoURL {
    return VideoURLToJSONTyped(json, false);
}

export function VideoURLToJSONTyped(value?: VideoURL | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
    };
}

